---
- hosts: web
  become: true

  vars:
    image_name: infra-devops
    container_name: infra-devops-container

  tasks:

    - name: Copy Docker image
      copy:
        src: ../app/infra-devops.tar
        dest: /tmp/infra-devops.tar

    - name: Stop old container
      shell: docker stop {{ container_name }}
      ignore_errors: yes

    - name: Remove old container
      shell: docker rm {{ container_name }}
      ignore_errors: yes

    - name: Remove old image
      shell: docker rmi {{ image_name }}:latest
      ignore_errors: yes

    - name: Load Docker image
      shell: docker load -i /tmp/infra-devops.tar

    - name: Run Docker container
      shell: |
        docker run -d \
        --name {{ container_name }} \
        -p 80:80 \
        --restart unless-stopped \
        {{ image_name }}:latest